return {
  chevron = "",
  calendar = "",
  clock = "󰥔",
  cpu = "􀧓",
  memory = "󰍛",
  battery = {
    full = "􀛨", high = "􀺸", mid = "􀺶",
    low = "􀛩", empty = "􀛪", charging = "􀢋",
  },
  volume = {
    high = "󰕾", mid = "󰖀",
    low = "󰕿", muted = "󰖁",
  },
  wifi = { connected = "󰖩", disconnected = "󰖪" },
  ethernet = "󰈀",
  bell = "",
  bell_dot = "󰧆",
  package = "󱄖",
  gear = "󰒓",
  music = "󰎇",
  media = { back = "󰒮", play = "󰐊", pause = "󰏤", forward = "󰒭" },
  apple = "",
  lock = "󰌾",
  sleep = "󰒲",
  restart = "󰜉",
  shutdown = "󰐥",
  thermometer = "󰔏",
  down = "󰁅",
  up = "󰁝",
  resize = "󰘖",
  service = "󰒓",
}
