#!/usr/bin/env bash

readonly GAP=8
readonly BAR_OFFSET=42

yabai -m config layout bsp

yabai -m config top_padding "$GAP"
yabai -m config bottom_padding "$GAP"
yabai -m config left_padding "$GAP"
yabai -m config right_padding "$GAP"
yabai -m config window_gap "$GAP"

yabai -m config external_bar all:"$BAR_OFFSET":0

yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config window_placement second_child

yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" title="Info$" manage=off
yabai -m rule --add app="^Raycast" manage=off
yabai -m rule --add app="^Claude$" manage=off
yabai -m rule --add app="^Zoom$" manage=off
yabai -m rule --add app="^Tailscale$" manage=off
